costs:
  false_negative: 30.0
  false_positive: 1.0
data:
  exclude_columns: []
  path: data/IC Weld.csv
  random_state: 42
  target_column: GT_Label
  test_size: 0.2
  good_tag: Good
  bad_tag: Bad
export:
  export_onnx: true
  onnx_opset_version: 12
  save_models: true
  save_plots: true
  save_predictions: true
features:
  correlation_threshold: 1.0
  filter_data: false
  variance_threshold: 0.0
hyperparam_spaces:
  RandomForest:
    bootstrap:
    - true
    class_weight:
    - balanced_subsample
    max_depth:
    - null
    - 5
    - 10
    max_features:
    - sqrt
    min_samples_leaf:
    - 1
    - 2
    - 5
    min_samples_split:
    - 2
    - 5
    - 10
    n_estimators:
    - 100
    - 200
    - 300
    oob_score:
    - true
  XGBoost:
    colsample_bytree:
    - 0.6
    - 0.8
    - 1.0
    eval_metric:
    - logloss
    gamma:
    - 0
    - 0.1
    - 0.2
    learning_rate:
    - 0.01
    - 0.05
    - 0.1
    max_depth:
    - 3
    - 4
    - 5
    - 6
    min_child_weight:
    - 3
    - 5
    - 7
    n_estimators:
    - 100
    - 200
    - 400
    scale_pos_weight:
    - 62.5
    subsample:
    - 0.6
    - 0.8
    - 1.0
logging:
  enabled: true
  summary: true
model_params:
  RandomForest:
    bootstrap: true
    class_weight: balanced_subsample
    max_depth: 6
    max_features: sqrt
    min_samples_leaf: 5
    min_samples_split: 10
    n_estimators: 300
    n_jobs: -1
    oob_score: true
    random_state: 42
  XGBoost:
    colsample_bytree: 0.8
    eval_metric: logloss
    gamma: 0.1
    learning_rate: 0.1
    max_depth: 4
    min_child_weight: 5
    n_estimators: 400
    n_jobs: -1
    objective: binary:logistic
    random_state: 42
    scale_pos_weight: 62.5
    subsample: 0.8
models:
  base_model_columns:
  - AnomalyScore
  - Good
  base_model_decisions: []
  enabled:
  - XGBoost
  - RandomForest
optimization:
  enabled: false
  iterations: 10
  n_jobs: -1
  optimize_final_model: true
output:
  base_dir: output
  subdirs:
    logs: logs
    models: models
    plots: plots
    predictions: predictions
    streamlit_data: streamlit_data
training:
  n_splits: 5
  smote_ratio: 0.5
  use_kfold: true
  use_smote: true
bitwise_logic:
  rules: []
  enabled: true
model_zoo:
  selected_model: XGBoost
