version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./data:/app/data
      - ./output:/app/output
    environment:
      - PYTHONPATH=/app
    command: uvicorn backend.api.main:app --host 0.0.0.0 --port 8000 --reload

  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
    ports:
      - "8501:8501"
    volumes:
      - ./output:/app/output
    environment:
      - BACKEND_URL=http://backend:8000
    depends_on:
      - backend
    command: streamlit run frontend/streamlit/app.py --server.port=8501 --server.address=0.0.0.0

volumes:
  data:
  output: 